import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          {/* favicon */}
          {/* fuentes web (google font) */}
          {/* hojas de estilos de liberías de internet */}
          {/* script/js podemos agregar scripts que traigamos desde internet */}
          <title>Avocado App</title>
          <meta name="description" content="Generated by create next app" />
          {/* <link rel="icon" href="/favicon.ico" /> */}
          <link
            rel="shortcut icon"
            href="./svgviewer-png-output.png"
            type="image/x-icon"
          />
          <meta name="author" content="Daniel Alejandro Briceño Salazar" />
          <meta
            name="image"
            property="og:image"
            content="https://raw.githubusercontent.com/dbriceno10/curso-nextjs-platzi/master/pages/miniatura.png"
          />
          <meta
            name="description"
            property="og:description"
            content="Hola, mi nombre es Daniel Briceño, soy Full Sack Developer.

      Soy entusiasta de la educación digital y apasionado de la educación efectiva, del rápido aprendizaje y del crecimiento personal y profesional, me encanta crear productos digitales. Aunque mi especialidad es frontend, hoy me estoy desarrollando como especialista en backend para ser un fullstack web javascript developer. 
      
      La comunicación y el trabajo en equipo es para mí esencial para poder crecer como desarrollador. Soy proactivo y metódico, siempre busco nuevos retos y me adapto fácilmente a los cambios, estoy abierto a aprender nuevas tecnologías y lenguajes.
      
      Mis Skills: HTML, CSS, JavaScript, React JS, React-Redux, TypeScript, Bootstrap, Less, Node JS, Express, SQL, PostgreSQL, Sequelize, MongoDB, Mongoose, JsonWebToken, Figma, Git."
          />
        </Head>
        {/* Podemos tener mayores controles sobre el body como añadir clases de css por ejemplo */}
        <body>
          <Main />
          <NextScript />
          {/* Podemos agregar agregar elementos adocionales que apliquen para todo el documento y todas las páginas, pero esto no es muy común */}
        </body>
      </Html>
    );
  }
}

export default MyDocument;
